name: KoharuBanJava
version: '0.1.0-dev'
main: github.daisukiKaffuChino.koharu.KoharuBan
api-version: '1.20'
author: daisukiKaffuChino
website: https://github.com/daisukiKaffuChino/KoharuBan-Java
load: STARTUP

commands:
  koharu:
    description: "重新加载插件配置/查询主手物品附魔Key"
    usage: "/koharu reload/key"